// js/data.js — default seed listings
// These load the first time the app opens. After that, localStorage takes over.

const SEED_DATA = [
  { id:'s1', address:'4821 Secor Rd', zip:'43623', county:'Lucas', market:'lucas', stage:'Auction', filed:'2025-10-14', auction:'2026-04-18', est_value:87000, source:'Lucas Co. Sheriff', url:'https://www.lucascountysheriff.org/civil/sheriff-sales', notes:'', tax_owed:null, redemption_period:'', tax_rate:null },
  { id:'s2', address:'1143 Bancroft St', zip:'43607', county:'Lucas', market:'lucas', stage:'Filing', filed:'2026-01-22', auction:'', est_value:63000, source:'Lucas Co. Auditor', url:'', notes:'', tax_owed:null, redemption_period:'', tax_rate:null },
  { id:'s3', address:'3302 Lagrange St', zip:'43608', county:'Lucas', market:'lucas', stage:'Pre-Foreclosure', filed:'2026-03-01', auction:'', est_value:55000, source:'ATTOM Data', url:'', notes:'', tax_owed:null, redemption_period:'', tax_rate:null },
  { id:'s4', address:'710 Fulton St', zip:'43605', county:'Lucas', market:'lucas', stage:'REO', filed:'2025-09-30', auction:'', est_value:47500, source:'Fannie Mae HomePath', url:'https://www.homepath.com', notes:'', tax_owed:null, redemption_period:'', tax_rate:null },
  { id:'s5', address:'214 Oak St', zip:'43604', county:'Lucas', market:'lucas', stage:'Tax Lien', filed:'2026-01-10', auction:'2026-06-05', est_value:52000, source:'Lucas Co. Treasurer', url:'https://co.lucas.oh.us/treasurer', notes:'Delinquent since 2023. Verify IRS liens.', tax_owed:3800, redemption_period:'1 year', tax_rate:18 },
  { id:'s6', address:'918 Collingwood Blvd', zip:'43612', county:'Lucas', market:'lucas', stage:'Tax Deed', filed:'2025-11-15', auction:'2026-04-30', est_value:41000, source:'Lucas Co. Treasurer', url:'', notes:'Redemption period expired. Title issues possible.', tax_owed:7200, redemption_period:'Expired', tax_rate:18 },
  { id:'s7', address:'3238 Van Fleet Pkwy', zip:'43617', county:'Lucas', market:'lucas', stage:'Land Bank', filed:'2026-02-01', auction:'', est_value:68000, source:'Toledo Land Bank', url:'https://www.toledolucascountylandbank.com', notes:'Rehabbed. Sylvania Schools district.', tax_owed:null, redemption_period:'', tax_rate:null },
  { id:'s8', address:'5718 Glendale Ave', zip:'43614', county:'Lucas', market:'lucas', stage:'Auction', filed:'2025-11-11', auction:'2026-04-25', est_value:101000, source:'Lucas Co. Sheriff', url:'https://www.lucascountysheriff.org/civil/sheriff-sales', notes:'', tax_owed:null, redemption_period:'', tax_rate:null },
  { id:'s9', address:'8823 Gate House Rd', zip:'22079', county:'Fairfax', market:'dmv', stage:'Auction', filed:'2025-12-05', auction:'2026-04-22', est_value:498000, source:'Fairfax Circuit Ct.', url:'https://icare.fairfaxcounty.gov', notes:'', tax_owed:null, redemption_period:'', tax_rate:null },
  { id:'s10', address:'1102 Lamont St NW', zip:'20010', county:'DC', market:'dmv', stage:'Filing', filed:'2026-01-30', auction:'', est_value:785000, source:'ATTOM Data', url:'', notes:'', tax_owed:null, redemption_period:'', tax_rate:null },
  { id:'s11', address:'421 N Glebe Rd #405', zip:'22203', county:'Arlington', market:'dmv', stage:'REO', filed:'2025-08-15', auction:'', est_value:412000, source:'Fannie Mae HomePath', url:'https://www.homepath.com', notes:'', tax_owed:null, redemption_period:'', tax_rate:null },
  { id:'s12', address:'9024 Liberia Ave', zip:'20110', county:'Manassas', market:'dmv', stage:'Pre-Foreclosure', filed:'2026-02-28', auction:'', est_value:331000, source:'ATTOM Data', url:'', notes:'', tax_owed:null, redemption_period:'', tax_rate:null },
  { id:'s13', address:'302 Battlefield Pkwy', zip:'20176', county:'Loudoun', market:'dmv', stage:'Auction', filed:'2025-11-20', auction:'2026-05-07', est_value:617000, source:'Loudoun Co. Records', url:'', notes:'', tax_owed:null, redemption_period:'', tax_rate:null },
  { id:'s14', address:'4402 8th St NE', zip:'20017', county:'DC', market:'dmv', stage:'Tax Lien', filed:'2026-02-15', auction:'2026-07-18', est_value:620000, source:'DC OTR', url:'https://otr.cfo.dc.gov/page/tax-sale', notes:'DC annual tax lien sale. High redemption rate in this area.', tax_owed:12400, redemption_period:'6 months', tax_rate:18 },
  { id:'s15', address:'11203 Veirs Mill Rd', zip:'20902', county:'Montgomery MD', market:'dmv', stage:'Tax Deed', filed:'2025-10-20', auction:'2026-05-12', est_value:389000, source:'Montgomery Co. Finance', url:'https://www.montgomerycountymd.gov/finance/tax-sale.html', notes:'Check IRS/municipal liens before bidding.', tax_owed:18700, redemption_period:'Expired', tax_rate:6 },
];
